# Generated by Django 3.2.25 on 2024-04-23 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('lab', 'Lab'), ('lecture', 'Lec')], default='lecture', max_length=7)),
                ('course_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta_app.course')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('Admin', 'Ad'), ('Teacher-Assistant', 'Ta'), ('Instructor', 'In')], default='Teacher-Assistant', max_length=17)),
                ('phone_number', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=256)),
                ('assigned_sections', models.ManyToManyField(to='ta_app.Section')),
            ],
        ),
    ]
