# Generated by Django 5.0.4 on 2024-05-16 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='type',
            field=models.CharField(choices=[('LAB', 'Lab'), ('LEC', 'Lec'), ('DIS', 'Dis')], default='LEC', max_length=10),
        ),
    ]
