# Generated by Django 3.2.25 on 2024-05-07 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='assigned_section',
            field=models.ManyToManyField(blank=True, related_name='assigned_users', to='ta_app.Section'),
        ),
    ]
