# Generated by Django 5.0.3 on 2024-05-02 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Mo', 'Monday'), ('Tu', 'Tuesday'), ('We', 'Wednesday'), ('Th', 'Thursday'), ('Fr', 'Friday')], max_length=9)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='meeting_time',
            field=models.CharField(help_text='Format: HH:MM-HH:MM AM/PM', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='assigned_section',
            field=models.ManyToManyField(blank=True, related_name='assigned_users', to='ta_app.section'),
        ),
        migrations.AddField(
            model_name='section',
            name='meeting_days',
            field=models.ManyToManyField(blank=True, to='ta_app.day'),
        ),
    ]
