# Generated by Django 5.0.4 on 2024-05-05 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Mo', 'Monday'), ('Tu', 'Tuesday'), ('We', 'Wednesday'), ('Th', 'Thursday'), ('Fr', 'Friday')], max_length=9)),
            ],
        ),
        migrations.RemoveField(
            model_name='section',
            name='meeting_time',
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('Fall', 'Fall'), ('Winter', 'Wint'), ('Spring', 'Spri'), ('Summer', 'Summ')], default='Fall', max_length=6),
        ),
        migrations.AddField(
            model_name='section',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='location',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='meeting_days',
            field=models.ManyToManyField(blank=True, to='ta_app.day'),
        ),
    ]
