# Generated by Django 3.2.25 on 2024-04-23 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='section_type',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='assigned_sections',
        ),
        migrations.AddField(
            model_name='course',
            name='course_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='meeting_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='section_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='assigned',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='assigned_section',
            field=models.ManyToManyField(blank=True, to='ta_app.Section'),
        ),
    ]
