# Generated by Django 5.0.4 on 2024-04-29 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_app', '0002_course_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
