# Generated by Django 5.0.4 on 2024-04-29 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_app', '0003_section_end_time_section_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='meeting_time',
        ),
        migrations.AddField(
            model_name='section',
            name='location',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
