# Generated by Django 5.0.4 on 2024-04-30 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_app', '0004_remove_section_meeting_time_section_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='assigned_section',
            field=models.ManyToManyField(blank=True, related_name='assigned_users', to='ta_app.section'),
        ),
    ]
