# Generated by Django 5.0.4 on 2024-05-11 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_app', '0006_alter_user_assigned_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='grader_status',
            field=models.BooleanField(default=False),
        ),
    ]
