# Generated by Django 5.0.4 on 2024-05-02 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_app', '0006_alter_section_end_time_alter_section_start_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_name',
            new_name='course_subject',
        ),
        migrations.AddField(
            model_name='course',
            name='course_title',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
