# Generated by Django 5.0.4 on 2024-05-03 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_app', '0007_rename_course_name_course_course_subject_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_subject',
            new_name='course_name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_title',
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='assigned_section',
            field=models.ManyToManyField(blank=True, to='ta_app.section'),
        ),
    ]
